spring:
  datasource:
    url: jdbc:mysql://${datasourceURL}?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${datasourceUsername}
    password: ${datasourcePassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace